// SEO Configuration
export const seoConfig = {
  site: {
    name: "Marcos Pilgrim - Portfólio",
    url: "https://marcospilgrim.com.br",
    title: "Marcos Pilgrim - Desenvolvedor Full Stack, Designer Gráfico e Escritor",
    description:
      "Portfólio digital de Marcos Pilgrim, desenvolvedor full-stack, designer gráfico e escritor. Conheça meus principais projetos, habilidades e experiências profissionais.",
    image: "https://marcospilgrim.com.br/marcos_pilgrim_portfolio_og_image.webp",
    imageAlt: "Marcos Pilgrim - Portfólio Digital",
    locale: "pt_BR",
    type: "website",
  },
  author: {
    name: "Marcos Pilgrim",
    jobTitle: "Full Stack Developer, Graphic Designer, Writer",
    email: "marcos@example.com",
    url: "https://marcospilgrim.com.br",
    image: "https://marcospilgrim.com.br/marcos_pilgrim_portfolio_og_image.webp",
  },
  social: {
    github: "https://github.com/MarcosAlves90",
    linkedin: "https://www.linkedin.com/in/marcos-alves-dev",
    instagram: "https://www.instagram.com/marcos.pilgrim",
  },
  keywords: [
    "desenvolvedor",
    "desenvolvedor full-stack",
    "desenvolvedor web",
    "desenvolvedor freelance",
    "desenvolvedor full stack freelance",
    "contratar desenvolvedor",
    "contratar desenvolvedor full-stack",
    "portfólio desenvolvedor",
    "portfólio desenvolvedor full stack",
    "portfólio projetos",
    "desenvolvimento web",
    "criação de sites",
    "landing page",
    "landing page de alta conversão",
    "criação de landing page",
    "sites institucionais",
    "e-commerce desenvolvimento",
    "loja virtual",
    "preço desenvolvimento site",
    "orçamento desenvolvimento de site",
    "apps mobile",
    "aplicativos mobile MVP",
    "desenvolvimento de aplicativos",
    "software sob medida",
    "SaaS desenvolvimento",
    "manutenção de sites",
    "suporte técnico site",
    "otimização de velocidade",
    "core web vitals",
    "consultoria SEO técnico",
    "otimização de imagens",
    "Cloudinary",
    "React",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Firebase",
    "PostgreSQL",
    "MongoDB",
    "Docker",
    "Figma",
    "UX UI design",
    "designer gráfico",
    "design gráfico para empresas",
    "copywriting para conversão",
    "integração de pagamentos",
    "integração com APIs",
    "consultoria de performance",
    "desenvolvedor São Paulo",
    "desenvolvedor web São Paulo",
    "freelance web developer",
    "case study desenvolvimento",
    "projeto e-commerce",
    "projeto institucional",
    "desenvolvimento web responsivo",
    "projetos com Tailwind CSS",
    "portfólio React Next.js",
  ],
  pages: {
    home: {
      title: "Desenvolvedor Full Stack, Designer Gráfico e Escritor",
      description:
        "Marcos Pilgrim — desenvolvedor full-stack e designer gráfico focado em performance e conversão. Contrate landing pages, sites institucionais e aplicativos com manutenção técnica.",
      path: "/",
    },
    projects: {
      title: "Todos os Projetos",
      description:
        "Cases técnicos e estudos de caso com tecnologias (React, Next.js, Vue.js, TypeScript) e resultados obtidos. Veja detalhes e demos.",
      path: "/projetos",
    },
    services: {
      title: "Serviços e Preços",
      description:
        "Serviços comerciais: landing pages, sites institucionais, e-commerces e aplicativos. Pacotes, preços e orçamento via WhatsApp para projetos com foco em conversão.",
      path: "/servicos",
    },
  },
};
